using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LocalNEXUS.App.Services.Editing;

/// <summary>How a file was read before an edit was asked for.</summary>
public enum FileReadState
{
    /// <summary>The whole file is in hand and will be shown to the model.</summary>
    Whole,

    /// <summary>Too large to send whole, so the part being edited was taken.</summary>
    Excerpted,

    /// <summary>It is not there. Nothing can be edited.</summary>
    Missing,

    /// <summary>It is there and could not be read. Nothing can be edited.</summary>
    Unreadable
}

/// <summary>What a read produced, and whether it is enough to edit from.</summary>
/// <param name="State">Which of the four answers this is.</param>
/// <param name="Content">The file, or the region of it, or empty when it could not be read.</param>
/// <param name="Note">What to tell the model about what it is looking at, or empty.</param>
/// <param name="Message">What to tell a person when this is not usable.</param>
public sealed record FileReading(FileReadState State, string Content, string Note, string Message)
{
    /// <summary>True when there is something to edit from.</summary>
    public bool IsUsable => State is FileReadState.Whole or FileReadState.Excerpted;
}

/// <summary>
/// Reads a file from disk immediately before a model is asked to change it.
/// </summary>
/// <remarks>
/// A model must never be asked to edit a file it has not just been shown, and shown from disk
/// rather than from the index, a cache, or something said earlier in the same run. Those are all
/// answers to the question of what the file used to hold. The file may have been written by the
/// last step of this very plan, edited by hand while the run was going, or regenerated by a build,
/// and a model shown a stale copy will faithfully produce a change against a file that no longer
/// exists in that shape.
///
/// This is the antidote to the failure it keeps producing, which is the model inventing the lines
/// it claims to be replacing. It cannot invent what it was just handed, and the measurements say it
/// will otherwise: the model in use here scores 0.03 exact match at generating a diff, so asking it
/// to remember a file it was shown earlier is asking the wrong thing of it twice over.
///
/// Never throws. A file that is not there and a file that cannot be read are answers, and the
/// caller refuses the edit rather than proceeding on nothing.
/// </remarks>
public static class SourceFileReader
{
    /// <summary>
    /// How much of a file is sent whole before only the edited region is sent.
    /// </summary>
    /// <remarks>
    /// Roughly four hundred lines of C#. Under it, sending everything costs some context and buys
    /// certainty, which is the trade worth making in every direction here. Over it, a whole file
    /// crowds out the plan, the signatures and the reply ceiling all at once, and the model starts
    /// losing the middle of what it was shown, which is the same failure by a slower route.
    /// </remarks>
    public const int WholeFileBudget = 16_000;

    /// <summary>How many lines of context are kept either side of the region being edited.</summary>
    private const int RegionPadding = 12;

    /// <summary>
    /// Reads the file a task is about to change.
    /// </summary>
    /// <param name="projectPath">The open project, which every relative path is inside.</param>
    /// <param name="relativePath">Where the file is, relative to the project root.</param>
    /// <param name="typeName">The type being changed, used to pick the region of a large file.</param>
    public static FileReading Read(string? projectPath, string relativePath, string typeName)
    {
        if (string.IsNullOrWhiteSpace(projectPath))
        {
            return new FileReading(
                FileReadState.Missing,
                string.Empty,
                string.Empty,
                "No project is open, so there is nothing to read this file from.");
        }

        string absolute;

        try
        {
            absolute = Path.GetFullPath(Path.Combine(projectPath, relativePath));
        }
        catch (Exception ex) when (ex is ArgumentException or NotSupportedException or PathTooLongException)
        {
            return new FileReading(FileReadState.Unreadable, string.Empty, string.Empty, $"{relativePath} is not a usable path.");
        }

        if (!File.Exists(absolute))
        {
            return new FileReading(
                FileReadState.Missing,
                string.Empty,
                string.Empty,
                $"{relativePath} is not there any more, so there is nothing to change.");
        }

        string content;

        try
        {
            content = File.ReadAllText(absolute);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            return new FileReading(
                FileReadState.Unreadable,
                string.Empty,
                string.Empty,
                $"{relativePath} could not be read, so it was not changed: {ex.Message}");
        }

        if (content.Length <= WholeFileBudget)
        {
            return new FileReading(FileReadState.Whole, content, string.Empty, string.Empty);
        }

        return Excerpt(content, relativePath, typeName);
    }

    /// <summary>
    /// Takes the part of a large file that is being changed, with the shape of the rest around it.
    /// </summary>
    /// <remarks>
    /// The region is found by parsing rather than by counting lines from the index, because the
    /// index records where a type starts and not where it ends, and an edit shown half a type is
    /// worse than one shown none of it. What goes with it is the file's usings, its namespace, and
    /// one line per member of every type in the file, so the model can see what exists around the
    /// region without being sent all of it.
    ///
    /// A file whose target cannot be found falls back to its opening, which is where the usings and
    /// the first declarations are, and says so. Guessing at a middle would be worse.
    /// </remarks>
    private static FileReading Excerpt(string content, string relativePath, string typeName)
    {
        var text = content.ReplaceLineEndings("\n");
        var lines = text.Split('\n');

        SyntaxNode root;

        try
        {
            root = CSharpSyntaxTree.ParseText(text).GetRoot();
        }
        catch (Exception ex) when (ex is ArgumentException or InvalidOperationException)
        {
            return Head(lines, relativePath, "It could not be parsed, so this is the start of it.");
        }

        var target = root.DescendantNodes()
            .OfType<BaseTypeDeclarationSyntax>()
            .FirstOrDefault(t => string.Equals(t.Identifier.Text, typeName, StringComparison.Ordinal));

        if (target is null)
        {
            return Head(lines, relativePath, $"{typeName} was not found in it, so this is the start of it.");
        }

        var span = target.GetLocation().GetLineSpan();
        var first = Math.Max(0, span.StartLinePosition.Line - RegionPadding);
        var last = Math.Min(lines.Length - 1, span.EndLinePosition.Line + RegionPadding);

        var region = string.Join(Environment.NewLine, lines[first..(last + 1)]);

        var note =
            $"{relativePath} is too large to send whole, so what follows is lines {first + 1} to {last + 1} "
            + $"of it, holding {typeName}. The rest of the file is unchanged and is not shown. "
            + $"Everything the file declares:{Environment.NewLine}{Outline(root)}";

        return new FileReading(FileReadState.Excerpted, region, note, string.Empty);
    }

    private static FileReading Head(string[] lines, string relativePath, string why)
    {
        var count = Math.Min(lines.Length, 200);
        var region = string.Join(Environment.NewLine, lines[..count]);

        return new FileReading(
            FileReadState.Excerpted,
            region,
            $"{relativePath} is too large to send whole. {why} Lines 1 to {count} follow.",
            string.Empty);
    }

    /// <summary>One line per type and member, which is the shape of the file without its bodies.</summary>
    private static string Outline(SyntaxNode root)
    {
        var lines = new List<string>();

        foreach (var type in root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
        {
            var keyword = type is TypeDeclarationSyntax declaration ? declaration.Keyword.Text : "enum";

            lines.Add($"  {keyword} {type.Identifier.Text}");

            foreach (var member in type.ChildNodes().OfType<MemberDeclarationSyntax>())
            {
                if (Describe(member) is { Length: > 0 } described)
                {
                    lines.Add($"    {described}");
                }
            }
        }

        return string.Join(Environment.NewLine, lines);
    }

    private static string Describe(MemberDeclarationSyntax member) => member switch
    {
        MethodDeclarationSyntax method => $"{method.ReturnType} {method.Identifier}{method.ParameterList}",
        PropertyDeclarationSyntax property => $"{property.Type} {property.Identifier}",
        FieldDeclarationSyntax field => $"{field.Declaration.Type} {string.Join(", ", field.Declaration.Variables)}",
        ConstructorDeclarationSyntax constructor => $"{constructor.Identifier}{constructor.ParameterList}",
        EventDeclarationSyntax @event => $"event {@event.Type} {@event.Identifier}",
        _ => string.Empty
    };
}
